### ISSUE TITLE
Best way to center?

### ISSUE THREAD

**Issue by ghostdevv** [gtm-nayan/svelte-yafal#2]
Having this issue:

![image](https://user-images.githubusercontent.com/47755378/171065056-e3d27d89-0e6b-4eb9-9474-9fc08b8cbfe5.png)

It's not vertically centred, I can use the `style` prop to center it but don't want to have to do it on every icon

**Comment by gtm-nayan** [comment]
The icons should already be centered within the SVG. For aligning the SVG itself, it'd be done from outside the component. I'll see if it can be made easier through a prop after inspecting it if you could make a REPL.
